from PyQt6 import QtCore, QtGui, QtWidgets


class GameOver(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Game Over")
        MainWindow.setWindowIcon(QtGui.QIcon("./assets/star.png"))
        MainWindow.resize(1494, 839)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(550, 120, 411, 151))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(550, 40, 411, 151))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(560, 230, 411, 151))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.net_worth = QtWidgets.QLabel(self.centralwidget)
        self.net_worth.setGeometry(QtCore.QRect(560, 320, 411, 151))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.net_worth.setFont(font)
        self.net_worth.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.net_worth.setObjectName("net_worth")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(290, 580, 181, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1020, 580, 181, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(670, 580, 181, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1494, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Game Over", "Game Over"))
        self.label.setText(_translate("Game Over", "Thanks for Playing!"))
        self.label_2.setText(_translate("Game Over", "GAME OVER"))
        self.label_3.setText(_translate("Game Over", "Your Final Net Worth"))
        self.net_worth.setText(_translate("Game Over", "$200,000"))
        self.pushButton.setText(_translate("Game Over", "Replay"))
        self.pushButton_2.setText(_translate("Game Over", "Quit Game"))
        self.pushButton_3.setText(_translate("Game Over", "See High Scores"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = GameOver()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
